
package view;
import controler.ControllerCliente;
import controler.ControllerFuncionario;
import java.util.ArrayList;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import model.Cliente;
import model.Funcionario;
public class FrmFuncionario extends javax.swing.JFrame {
    ControllerCliente controlCliente = new ControllerCliente();
    ControllerFuncionario controlFuncionario = new ControllerFuncionario();
    String selecc;
    Cliente clie = new Cliente();
    Funcionario func = new Funcionario();
    
    /**
     * Creates new form FrmOpcaoFuncionario
     */
    
    public FrmFuncionario() {
        initComponents();
        escondeTudo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnEditBebidas = new javax.swing.JButton();
        btnEdtFuncionario = new javax.swing.JButton();
        btnEditCliente = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblUtil = new javax.swing.JTable();
        txtNome = new javax.swing.JTextField();
        txtCpf = new javax.swing.JTextField();
        txtId = new javax.swing.JTextField();
        txtSenha = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        txtUsuario = new javax.swing.JTextField();
        lblId = new javax.swing.JLabel();
        lblNome = new javax.swing.JLabel();
        lblCpf = new javax.swing.JLabel();
        lblUsuario = new javax.swing.JLabel();
        lblSenha = new javax.swing.JLabel();
        lblEmail = new javax.swing.JLabel();
        btnAdd = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        lblEd = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnEditBebidas.setText("Editar Bebidas");
        btnEditBebidas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditBebidasActionPerformed(evt);
            }
        });

        btnEdtFuncionario.setText("Editar Funcionários");
        btnEdtFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEdtFuncionarioActionPerformed(evt);
            }
        });

        btnEditCliente.setText("Editar Clientes");
        btnEditCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditClienteActionPerformed(evt);
            }
        });

        tblUtil.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id", "nome", "cpf", "usuário", "senha", "email"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tblUtil.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblUtilMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblUtil);

        lblId.setText("ID:");

        lblNome.setText("nome:");

        lblCpf.setText("CPF:");

        lblUsuario.setText("Usuário: ");

        lblSenha.setText("Senha:");

        lblEmail.setText("Email:");

        btnAdd.setText("Adcionar");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnEditar.setText("Editar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        lblEd.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        lblEd.setText("EDIÇÃO DE ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnEditar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnEditBebidas)
                        .addGap(39, 39, 39)
                        .addComponent(btnEdtFuncionario)
                        .addGap(31, 31, 31)
                        .addComponent(btnEditCliente)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnAdd)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtId, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblUsuario, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblSenha, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblEmail, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lblId, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblNome, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 470, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(53, 53, 53))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblEd, javax.swing.GroupLayout.PREFERRED_SIZE, 373, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(61, 61, 61))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblEd, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblId)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblNome)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(7, 7, 7)
                        .addComponent(lblCpf)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(7, 7, 7)
                        .addComponent(lblUsuario)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8)
                        .addComponent(lblSenha)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8)
                        .addComponent(lblEmail)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(btnAdd)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEditBebidas)
                    .addComponent(btnEdtFuncionario)
                    .addComponent(btnEditCliente)
                    .addComponent(btnEditar))
                .addGap(21, 21, 21))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEditBebidasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditBebidasActionPerformed
        // TODO add your handling code here:
        new FrmTelaCadastroBebidas().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnEditBebidasActionPerformed

    private void btnEdtFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEdtFuncionarioActionPerformed
        // TODO add your handling code here:
        lblEd.setText("EDIÇÃO DE FUNCIONÁRIOS");
        mostraTudo();
        atualizaFuncionario();
        selecc = "Funcionario";
    }//GEN-LAST:event_btnEdtFuncionarioActionPerformed

    private void btnEditClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditClienteActionPerformed
        // TODO add your handling code here:
        lblEd.setText("EDIÇÃO DE CLIENTES");
        mostraTudo();
        atualizaCliente();
        selecc = "Cliente";
    }//GEN-LAST:event_btnEditClienteActionPerformed

    private void tblUtilMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblUtilMouseClicked
        // TODO add your handling code here:
        int linhaSelecionada = tblUtil.getSelectedRow();
        if(linhaSelecionada != -1){
            Object id = tblUtil.getValueAt(linhaSelecionada, 0);
            txtId.setText(id.toString());
            Object nome = tblUtil.getValueAt(linhaSelecionada, 1);
            txtNome.setText(nome.toString());
            Object cpf = tblUtil.getValueAt(linhaSelecionada, 2);
            txtCpf.setText(cpf.toString());
            Object usuario = tblUtil.getValueAt(linhaSelecionada, 3);
            txtUsuario.setText(usuario.toString());
            Object senha = tblUtil.getValueAt(linhaSelecionada, 4);
            txtSenha.setText(senha.toString());
            Object email = tblUtil.getValueAt(linhaSelecionada, 5);
            txtEmail.setText(email.toString());
        }
    }//GEN-LAST:event_tblUtilMouseClicked

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
        
        if(selecc == "Cliente"){
            clie.cpfCliente = txtCpf.getText();
            clie.emailCliente = txtEmail.getText();
            clie.nomeCliente = txtNome.getText();
            clie.senhaCliente = txtSenha.getText();
            clie.usuarioCliente = txtUsuario.getText();
            controlCliente.cadastroCliente(clie);
        }
        else if(selecc == "Funcionario"){
            func.cpfFunc = txtCpf.getText();
            func.emailFunc = txtEmail.getText();
            func.nomeFunc = txtNome.getText();
            func.senhaFunc = txtSenha.getText();
            func.usuarioFunc = txtUsuario.getText();
            controlFuncionario.cadastroFuncionario(func);
        }
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        // TODO add your handling code here:
        if(selecc == "Cliente"){
            clie.cpfCliente = txtCpf.getText();
            clie.emailCliente = txtEmail.getText();
            clie.idCliente = Integer.parseInt(txtId.getText());
            clie.nomeCliente = txtNome.getText();
            clie.senhaCliente = txtSenha.getText();
            clie.usuarioCliente = txtUsuario.getText();
            controlCliente.editarCliente(clie);
            atualizaCliente();
        }
        else if(selecc == "Funcionario"){
            func.cpfFunc = txtCpf.getText();
            func.emailFunc = txtEmail.getText();
            func.idFunc = Integer.parseInt(txtId.getText());
            func.nomeFunc = txtNome.getText();
            func.senhaFunc = txtSenha.getText();
            func.usuarioFunc = txtUsuario.getText();
            controlFuncionario.editarFuncionario(func);
            atualizaFuncionario();
        }
    }//GEN-LAST:event_btnEditarActionPerformed

    /**
     * @param args the command line arguments
     */
    
    public void escondeTudo(){
        lblCpf.setVisible(false);
        lblEd.setVisible(false);
        lblEmail.setVisible(false);
        lblId.setVisible(false);
        lblNome.setVisible(false);
        lblSenha.setVisible(false);
        lblUsuario.setVisible(false);
        txtId.setVisible(false);
        txtCpf.setVisible(false);
        txtEmail.setVisible(false);
        txtNome.setVisible(false);
        txtSenha.setVisible(false);
        txtUsuario.setVisible(false);
        btnAdd.setVisible(false);
        btnEditar.setVisible(false);
        tblUtil.setVisible(false);
    }
    
    public void mostraTudo(){
        lblCpf.setVisible(true);
        lblEd.setVisible(true);
        lblEmail.setVisible(true);
        lblId.setVisible(true);
        lblNome.setVisible(true);
        lblSenha.setVisible(true);
        lblUsuario.setVisible(true);
        txtId.setVisible(true);
        txtCpf.setVisible(true);
        txtEmail.setVisible(true);
        txtNome.setVisible(true);
        txtSenha.setVisible(true);
        txtUsuario.setVisible(true);
        btnAdd.setVisible(true);
        btnEditar.setVisible(true);
        tblUtil.setVisible(true);
    }
    
    public void atualizaCliente(){
        List<Cliente> lista = new ArrayList();
        DefaultTableModel tbCliente = (DefaultTableModel) tblUtil.getModel();
        lista = controlCliente.pegaTudoCliente();
        tbCliente.setRowCount(0);
        for (Cliente cliente : lista) {
            Object[] dadosBebida = new Object[]{ cliente.idCliente, cliente.nomeCliente, cliente.cpfCliente, cliente.usuarioCliente, cliente.senhaCliente, cliente.emailCliente};
            tbCliente.addRow(dadosBebida);
        }
        tbCliente.fireTableDataChanged();
    }
    
    public void atualizaFuncionario(){
        List<Funcionario> lista = new ArrayList();
        DefaultTableModel tbCliente = (DefaultTableModel) tblUtil.getModel();
        lista = controlFuncionario.pegaTudoFuncionario();
        tbCliente.setRowCount(0);
        for (Funcionario funcionario : lista) {
            Object[] dadosBebida = new Object[]{ funcionario.idFunc, funcionario.nomeFunc, funcionario.cpfFunc, funcionario.usuarioFunc, funcionario.senhaFunc, funcionario.emailFunc};
            tbCliente.addRow(dadosBebida);
        }
        tbCliente.fireTableDataChanged();
    }
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmFuncionario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnEditBebidas;
    private javax.swing.JButton btnEditCliente;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnEdtFuncionario;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCpf;
    private javax.swing.JLabel lblEd;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblId;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblSenha;
    private javax.swing.JLabel lblUsuario;
    private javax.swing.JTable tblUtil;
    private javax.swing.JTextField txtCpf;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtSenha;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
