/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import javax.swing.JFrame;
import javax.swing.JOptionPane;
import controler.ControllerBebida;
import java.awt.Color;
import java.util.ArrayList;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import model.Bebida;
/**
 *
 * @author computador
 */
public class FrmTelaCadastroBebidas extends javax.swing.JFrame {
    ControllerBebida control = new ControllerBebida();
    Bebida bb = new Bebida();
    public FrmTelaCadastroBebidas() {
        initComponents();
        lblSup.setVisible(false);
        atualizarTabela();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtCodBebida = new javax.swing.JTextField();
        txtPreco = new javax.swing.JTextField();
        txtFindBId = new javax.swing.JTextField();
        btnAdcionar = new javax.swing.JButton();
        btnDeletar = new javax.swing.JButton();
        btnAtualizar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblBebida = new javax.swing.JTable();
        btnProcurar = new javax.swing.JToggleButton();
        txtEstoque = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        lblSup = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtNomeBebida1 = new javax.swing.JTextField();
        cbxTipoBebida = new javax.swing.JComboBox<>();
        btnVoltar = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Nome da bebida");

        jLabel6.setText("Preço");

        jLabel7.setText("Tipo da bebida");

        jLabel8.setText("Procure o codigo da bebida");

        txtCodBebida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodBebidaActionPerformed(evt);
            }
        });
        txtCodBebida.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCodBebidaKeyTyped(evt);
            }
        });

        txtPreco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPrecoActionPerformed(evt);
            }
        });

        btnAdcionar.setText("Adicionar");
        btnAdcionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdcionarActionPerformed(evt);
            }
        });

        btnDeletar.setText("Deletar");
        btnDeletar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeletarActionPerformed(evt);
            }
        });

        btnAtualizar.setText("Atualizar");
        btnAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtualizarActionPerformed(evt);
            }
        });

        tblBebida.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Nome bebida", "Tipo", "Preço", "Estoque"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Double.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tblBebida.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblBebidaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblBebida);

        btnProcurar.setText("Procurar");
        btnProcurar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProcurarActionPerformed(evt);
            }
        });

        jLabel2.setText("Estoque");

        lblSup.setText("jLabel3");

        jLabel3.setText("Código da bebida");

        txtNomeBebida1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeBebida1ActionPerformed(evt);
            }
        });

        cbxTipoBebida.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecionar", "Vodka", "Gin", "Whisky", "Cerveja", "Vinho" }));

        btnVoltar.setText("Voltar");
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(832, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(cbxTipoBebida, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtNomeBebida1, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblSup, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtCodBebida, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtPreco, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtFindBId, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(btnAdcionar)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnAtualizar)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnDeletar))
                                    .addComponent(txtEstoque, javax.swing.GroupLayout.Alignment.LEADING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnProcurar)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 546, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnVoltar, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(52, 52, 52))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtCodBebida, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtNomeBebida1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cbxTipoBebida, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtPreco, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtEstoque, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnAdcionar, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnAtualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnDeletar, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(lblSup)
                        .addGap(21, 21, 21)
                        .addComponent(jLabel8))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtFindBId, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnProcurar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtPrecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPrecoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPrecoActionPerformed

    private void btnProcurarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProcurarActionPerformed
        int cod = Integer.parseInt(txtFindBId.getText());
        bb = control.pegabebidaCod(cod);
        txtCodBebida.setText(String.valueOf(bb.codigoBebida));
        txtEstoque.setText(String.valueOf(bb.qtdeEstoque));
        txtNomeBebida1.setText(bb.nomeBebida);
        txtPreco.setText(String.valueOf(bb.precoBebida));
        if(bb.tipoBebida.equals("Vodka")){
                cbxTipoBebida.setSelectedItem("Vodka");
            }
            else if(bb.tipoBebida.equals("Gin")){
                cbxTipoBebida.setSelectedItem("Gin");
            }
            else if(bb.tipoBebida.equals("Vinho")){
                cbxTipoBebida.setSelectedItem("Vinho");
            }
            else if(bb.tipoBebida.equals("Whisky")){
                cbxTipoBebida.setSelectedItem("Whisky");
            }
            else if(bb.tipoBebida.equals("Cerveja")){
                cbxTipoBebida.setSelectedItem("Cerveja");
            }
    }//GEN-LAST:event_btnProcurarActionPerformed

    private void btnAdcionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdcionarActionPerformed
        // TODO add your handling code here:
        bb.nomeBebida = txtNomeBebida1.getText();
        String precoo = txtPreco.getText();
        String estoque = txtEstoque.getText();
        bb.tipoBebida = cbxTipoBebida.getSelectedItem().toString();
        if(precoo.equals("") || bb.nomeBebida.equals("") || estoque.equals("") || bb.tipoBebida.equals("Selecionar") ){
            lblSup.setText("preencha todos os campos(menos o campo codigo)");
            lblSup.setForeground(Color.red);
            lblSup.setVisible(true);
        }else{
        bb.precoBebida = Double.parseDouble(txtPreco.getText());
        bb.qtdeEstoque = Integer.parseInt(txtEstoque.getText());
        control.adcionarBebida(bb);
        atualizarTabela();
        txtCodBebida.setText("");
        txtEstoque.setText("");
        txtFindBId.setText("");
        txtNomeBebida1.setText("");
        txtPreco.setText("");
        cbxTipoBebida.setSelectedItem("Selecionar");
        }
    }//GEN-LAST:event_btnAdcionarActionPerformed

    private void txtNomeBebida1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeBebida1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeBebida1ActionPerformed

    private void btnDeletarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeletarActionPerformed
        // TODO add your handling code here:
        try{
            int cod = Integer.parseInt(txtCodBebida.getText());
            if(control.verificarCodBebida(cod)){
                control.excluirBebida(cod);
                lblSup.setText("Bebida deletada com sucesso");
                lblSup.setForeground(Color.blue);
                lblSup.setVisible(true);
            }else{
                lblSup.setText("Codigo bebida não encontrado");
                lblSup.setForeground(Color.red);
                lblSup.setVisible(true);
            }
        }catch(NumberFormatException e){
            System.out.println("numero invalido");
        }
        txtCodBebida.setText("");
        txtEstoque.setText("");
        txtFindBId.setText("");
        txtNomeBebida1.setText("");
        txtPreco.setText("");
        cbxTipoBebida.setSelectedItem("Selecionar");
        atualizarTabela();
    }//GEN-LAST:event_btnDeletarActionPerformed

    private void tblBebidaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblBebidaMouseClicked
        // TODO add your handling code here:
        int linhaSelecionada = tblBebida.getSelectedRow();
        if(linhaSelecionada != -1){
            Object codigoBebida = tblBebida.getValueAt(linhaSelecionada, 0);
            txtCodBebida.setText(codigoBebida.toString());
            Object nomeBebida = tblBebida.getValueAt(linhaSelecionada, 1);
            txtNomeBebida1.setText(nomeBebida.toString());
            Object tipoBebida = tblBebida.getValueAt(linhaSelecionada, 2);
            if(tipoBebida.equals("Vodka")){
                cbxTipoBebida.setSelectedItem("Vodka");
            }
            else if(tipoBebida.equals("Gin")){
                cbxTipoBebida.setSelectedItem("Gin");
            }
            else if(tipoBebida.equals("Vinho")){
                cbxTipoBebida.setSelectedItem("Vinho");
            }
            else if(tipoBebida.equals("Whisky")){
                cbxTipoBebida.setSelectedItem("Whisky");
            }
            else if(tipoBebida.equals("Cerveja")){
                cbxTipoBebida.setSelectedItem("Cerveja");
            }
            Object precoBebida = tblBebida.getValueAt(linhaSelecionada, 3);
            txtPreco.setText(precoBebida.toString());
            Object estoque = tblBebida.getValueAt(linhaSelecionada, 4);
            txtEstoque.setText(estoque.toString());
        }
    }//GEN-LAST:event_tblBebidaMouseClicked

    private void txtCodBebidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodBebidaActionPerformed

    }//GEN-LAST:event_txtCodBebidaActionPerformed

    private void btnAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtualizarActionPerformed
        bb.nomeBebida = txtNomeBebida1.getText();
        String precoo = txtPreco.getText();
        String estoque = txtEstoque.getText();
        String codigo = txtCodBebida.getText();
        bb.tipoBebida = cbxTipoBebida.getSelectedItem().toString();
        if(precoo.equals("") || codigo.equals("") || bb.nomeBebida.equals("") || estoque.equals("") || bb.tipoBebida.equals("Selecionar")){
            lblSup.setText("preencha todos os campos para editar");
            lblSup.setForeground(Color.red);
            lblSup.setVisible(true);
        }else{
        bb.precoBebida = Double.parseDouble(txtPreco.getText());
        bb.qtdeEstoque = Integer.parseInt(txtEstoque.getText());
        bb.codigoBebida = Integer.parseInt(txtCodBebida.getText());
        control.editarBebida(bb);
        atualizarTabela();
        txtCodBebida.setText("");
        txtEstoque.setText("");
        txtFindBId.setText("");
        txtNomeBebida1.setText("");
        txtPreco.setText("");
        cbxTipoBebida.setSelectedItem("Selecionar");
        }
    }//GEN-LAST:event_btnAtualizarActionPerformed

    private void txtCodBebidaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCodBebidaKeyTyped

    }//GEN-LAST:event_txtCodBebidaKeyTyped

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
        // TODO add your handling code here:
        new FrmFuncionario().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnVoltarActionPerformed
    
    public void atualizarTabela(){
        List<Bebida> lista = new ArrayList();
        DefaultTableModel tbBebida= (DefaultTableModel) tblBebida.getModel();
        lista = control.pegaBebida();
        tbBebida.setRowCount(0);
        for (Bebida bebida : lista) {
            Object[] dadosBebida = new Object[]{ bebida.codigoBebida, bebida.nomeBebida, bebida.tipoBebida, bebida.precoBebida, bebida.qtdeEstoque};
            tbBebida.addRow(dadosBebida);
        }
        tbBebida.fireTableDataChanged();
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmTelaCadastroBebidas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmTelaCadastroBebidas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmTelaCadastroBebidas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmTelaCadastroBebidas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmTelaCadastroBebidas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdcionar;
    private javax.swing.JButton btnAtualizar;
    private javax.swing.JButton btnDeletar;
    private javax.swing.JToggleButton btnProcurar;
    private javax.swing.JToggleButton btnVoltar;
    private javax.swing.JComboBox<String> cbxTipoBebida;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblSup;
    private javax.swing.JTable tblBebida;
    private javax.swing.JTextField txtCodBebida;
    private javax.swing.JTextField txtEstoque;
    private javax.swing.JTextField txtFindBId;
    private javax.swing.JTextField txtNomeBebida1;
    private javax.swing.JTextField txtPreco;
    // End of variables declaration//GEN-END:variables
}
